### ISSUE TITLE
No admin section

### ISSUE THREAD

**Issue by meirankri** [lodi-g/strapi-plugin-github-actions#4]
Hello and thank you for this repo,

I have an issue when i installed the plugin to my strapi 4.10.1,
I don't see the panel that suppose to be located in admin panel -> workflows.

**Comment by lodi-g** [comment]
Hi @meirankri,

Sorry I do not use this project anymore and hence will not maintain it. 
You're welcome to contribute through pull requests (or just fork it for your own version).

Cheers

**Comment by AndreCox** [comment]
Can you please add this into the readme so people don't waste time setting up a plugin that isn't supported
